function mutateGene(v,rate=.10){return Math.max(.12,Math.min(.96,v+(Math.random()-.5)*rate))}
function breedAgents(auto=false){normalizeAgents();const ranked=[...S.agents].sort((a,b)=>b.score-a.score),p1=ranked[0],p2=ranked[1]||ranked[0];const roles=[['Scout','Opportunity Scout','🔎'],['Closer','Pitch Optimizer','📣'],['Maker','Deliverable Builder','✍️'],['Guard','Proof Verifier','🛡️'],['Analyst','Research Synthesizer','🧪'],['Router','Task Router','🧭']];const r=roles[S.births%roles.length],genome={};GENES.forEach(k=>genome[k]=mutateGene(((p1.genome[k]||.5)+(p2.genome[k]||.5))/2,auto?.08:.14));S.births++;const child={id:id('AG'),name:r[0]+'-'+S.births,role:r[1],icon:r[2],gen:Math.max(p1.gen,p2.gen)+1,genome,score:genomeFitness(genome),status:'newborn'};if(S.agents.length>=9){const removable=[...S.agents].filter(a=>a.id!=='master').sort((a,b)=>a.score-b.score)[0];if(removable)S.agents=S.agents.filter(a=>a.id!==removable.id)}S.agents.push(child);log('birth','Local child agent bred',p1.name+' × '+p2.name+' → '+child.name);save();renderAll();if(!auto)toast('Best local genomes bred ✦')}
function spawnSubAgent(){breedAgents(false)}
function evolve(success=true){S.generation++;S.agents.forEach(a=>{GENES.forEach(k=>a.genome[k]=mutateGene(a.genome[k],success?.05:.17));a.gen=S.generation;a.score=genomeFitness(a.genome);a.status=success?'refined':'mutated'});for(const k in S.strategy)S.strategy[k]=mutateGene(S.strategy[k],success?.04:.12);log('train','Population genome mutated','Generation '+S.generation)}
function maybeTrain(){if(Date.now()-S.lastTrain>=7200000)trainNow(true);setInterval(()=>{if(Date.now()-S.lastTrain>=7200000)trainNow(true);renderTraining();renderTeacher()},60000)}
function renderTraining(){const rem=Math.max(0,7200000-(Date.now()-S.lastTrain)),min=Math.ceil(rem/60000);document.getElementById('nextTrain').textContent=min>60?Math.ceil(min/60)+'h':min+'m';document.getElementById('trainText').textContent='Every two hours the local GA mutates strategy weights using accepted-output signals. It catches up when the app reopens.';document.getElementById('trainBar').style.width=Math.min(100,(Date.now()-S.lastTrain)/7200000*100)+'%'}
function trainNow(auto=false){const gain=Math.min(.12,.025+S.accepted*.003);S.agents.forEach(a=>{GENES.forEach(k=>a.genome[k]=mutateGene(a.genome[k],gain));a.score=genomeFitness(a.genome);a.status='trained'});for(const k in S.strategy)S.strategy[k]=mutateGene(S.strategy[k],gain*.7);S.lastTrain=Date.now();S.xp+=20;log('train',auto?'Automatic two-hour mutation':'Manual genome mutation','Population '+S.agents.length);save();renderAll();if(!auto)toast('Local population mutated 🧬')}
function gradeText(text=''){let score=28;const words=text.trim().split(/\s+/).filter(Boolean);score+=Math.min(18,words.length/9);if(/next step|action|deliver|reply|confirm/i.test(text))score+=12;if(/scope|proof|evidence|transparent|limit/i.test(text))score+=12;if(/\n|•|1\./.test(text))score+=10;if(/customer|result|benefit|goal/i.test(text))score+=10;if(words.length>260)score-=10;return Math.max(10,Math.min(100,score))}
function runTeacher(auto=false){normalizeAgents();const samples=(S.acceptedOutputs||[]).slice(-8),outputScore=samples.length?samples.reduce((n,x)=>n+gradeText(x.text),0)/samples.length:50;S.agents.forEach(a=>{const gene=genomeFitness(a.genome);a.score=Math.round(gene*.65+outputScore*.25+(S.wins/(S.wins+S.fails+1))*10);a.status=a.score>=72?'elite':a.score>=55?'learning':'at risk'});const avg=S.agents.reduce((n,a)=>n+a.score,0)/S.agents.length;S.teacherScore=Math.round(avg);S.teacherReport=S.teacherScore>=75?'Strong population. Breed the top pair and target higher-value verified work.':S.teacherScore>=58?'Useful but inconsistent. Improve proof, specificity, and the final call to action.':'Weak generation. Retire the lowest agent, simplify the offer, and collect better accepted examples.';S.lastTeacher=Date.now();if(S.agents.length>1)breedAgents(true);log('train',auto?'SOL Teacher hourly review':'SOL Teacher manual review','Population grade '+S.teacherScore);save();renderAll();if(!auto)toast('SOL Teacher completed local review 🎓')}
function maybeTeacher(){if(Date.now()-S.lastTeacher>=3600000)runTeacher(true);setInterval(()=>{if(Date.now()-S.lastTeacher>=3600000)runTeacher(true)},60000)}
function renderTeacher(){const rem=Math.max(0,3600000-(Date.now()-S.lastTeacher)),min=Math.ceil(rem/60000);document.getElementById('teacherScore').textContent=S.teacherScore||50;document.getElementById('teacherReport').textContent=S.teacherReport||'Waiting for local review.';document.getElementById('nextTeacher').textContent=min>59?'1h':min+'m';document.getElementById('teacherBar').style.width=Math.min(100,(Date.now()-S.lastTeacher)/3600000*100)+'%'}
