const K='pennyspawn_v8';
const defaults={profile:null,wallet:{handle:'',lightning:'',url:''},ledger:[],activity:[],generation:1,wins:0,fails:0,births:1,accepted:0,acceptedOutputs:[],energy:20,xp:0,streak:0,lastCheckin:'',round:null,lastTrain:Date.now(),lastTeacher:Date.now(),teacherScore:50,teacherReport:'Waiting for the first local review.',strategy:{clarity:.55,urgency:.45,specificity:.52,trust:.58,brevity:.5},agents:[{id:'master',name:'Prime',role:'Master Operator',icon:'🧠',gen:1,score:50,status:'ready',genome:{clarity:.62,trust:.64,speed:.48,conversion:.52,proof:.66}}],sponsorUrl:'',btcPrice:0,baseRpc:'https://mainnet.base.org',baseRpcState:{status:'Not checked',block:'—',latency:'—'}};
let S=load(),timerHandle=null,worker=null,lastOutput='';
function load(){try{return deepMerge(structuredClone(defaults),JSON.parse(localStorage.getItem(K)||'{}'))}catch(e){return structuredClone(defaults)}}
function deepMerge(a,b){for(const k in b){if(b[k]&&typeof b[k]==='object'&&!Array.isArray(b[k]))a[k]=deepMerge(a[k]||{},b[k]);else a[k]=b[k]}return a}
function save(){localStorage.setItem(K,JSON.stringify(S))}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function fmt(n){return Math.max(0,Math.round(Number(n)||0)).toLocaleString()}
function usd(n){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n)||0)}
function id(p='PS'){return p+'-'+Date.now().toString(36).toUpperCase()+'-'+Math.random().toString(36).slice(2,6).toUpperCase()}
function toast(t){const e=document.createElement('div');e.className='toast';e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),2800)}
async function copyText(t){try{await navigator.clipboard.writeText(t);toast('Copied ⚡')}catch(e){prompt('Copy this:',t)}}
function log(type,text,meta=''){S.activity.unshift({id:id('EV'),type,text,meta,at:Date.now()});S.activity=S.activity.slice(0,80);save()}
function today(){return new Date().toISOString().slice(0,10)}
function createProfile(){let name=document.getElementById('signupName').value.trim(),handle=document.getElementById('signupHandle').value.trim().replace(/^@/,'');if(!name||handle.length<2)return toast('Enter your name and ZBD username.');S.profile={name,handle,createdAt:Date.now()};S.wallet.handle=handle;log('birth','Prime agent spawned','Generation 1');save();boot()}
function boot(){if(!S.profile){document.getElementById('signup').classList.add('on');return}document.getElementById('signup').classList.remove('on');document.getElementById('app').classList.remove('hidden');initWorker();normalizeAgents();renderAll();refreshPrice();maybeTrain();maybeTeacher();checkBaseRpc(false);if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})}
function showView(n){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+n));document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===n));window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));
function renderAll(){const income=S.ledger.filter(x=>x.type==='income').reduce((a,x)=>a+x.sats,0),out=S.ledger.filter(x=>x.type==='outgoing').reduce((a,x)=>a+x.sats+x.fee,0),bal=income-out;document.getElementById('balance').textContent=fmt(bal);document.getElementById('balanceUsd').textContent='≈ '+usd(S.btcPrice?bal/1e8*S.btcPrice:0);document.getElementById('balanceDot').className='dot '+(bal>0?'live':'');document.getElementById('generation').textContent=S.generation;document.getElementById('genMetric').textContent=S.generation;document.getElementById('roundWins').textContent=S.wins;document.getElementById('roundFails').textContent=S.fails;document.getElementById('acceptedMetric').textContent=S.accepted;document.getElementById('scoreMetric').textContent=Math.round(strategyScore());document.getElementById('profileName').textContent=S.profile.name;document.getElementById('profileHandle').textContent='@'+S.profile.handle;document.getElementById('level').textContent=14+Math.floor(S.xp/500);document.getElementById('streak').textContent=S.streak;document.getElementById('energy').textContent=S.energy;document.getElementById('births').textContent=S.births;document.getElementById('walletHandle').value='@'+(S.wallet.handle||S.profile.handle);document.getElementById('lightningAddress').value=S.wallet.lightning||'';document.getElementById('walletUrl').value=S.wallet.url||'';renderAgents();renderJobs();renderActivity();renderLedger();renderRound();renderTraining();renderTeacher();renderBaseRpc();document.getElementById('adStatus').textContent=S.sponsorUrl?'Sponsor connected. Watching can grant Agent Energy after the user returns.':'Rewarded ad provider is not connected. Owner can configure a sponsor URL in Settings.'}
function strategyScore(){return Object.values(S.strategy).reduce((a,b)=>a+b,0)/Object.keys(S.strategy).length*100}
const GENES=['clarity','trust','speed','conversion','proof'];
function randomGenome(){return Object.fromEntries(GENES.map(k=>[k,.35+Math.random()*.4]))}
function normalizeAgents(){S.agents.forEach((a,i)=>{a.genome=a.genome||randomGenome();a.score=Number(a.score)||50;a.status=a.status||'ready';a.gen=a.gen||S.generation});save()}
function genomeFitness(g){const weights={clarity:.24,trust:.22,speed:.14,conversion:.22,proof:.18};return GENES.reduce((n,k)=>n+(g[k]||.5)*weights[k],0)*100}
function agentSpecialty(a){const k=[...GENES].sort((x,y)=>(a.genome[y]||0)-(a.genome[x]||0))[0];return ({clarity:'Clear Writer',trust:'Trust Guard',speed:'Rapid Maker',conversion:'Closer',proof:'Proof Analyst'})[k]}
function renderAgents(){const box=document.getElementById('agentGrid');box.innerHTML=[...S.agents].sort((a,b)=>b.score-a.score).map(a=>`<article class="agent"><div class="agentTop"><div class="avatar">${a.icon}</div><span class="tag">GEN ${a.gen}</span></div><h3>${esc(a.name)}</h3><p>${esc(agentSpecialty(a))} · ${esc(a.role)}</p><div class="genome">${GENES.map(k=>`<span class="gene"><i style="width:${Math.round((a.genome[k]||0)*100)}%"></i></span>`).join('')}</div><div class="mini"><div><small>Fitness</small><b>${Math.round(a.score)}</b></div><div><small>Status</small><b>${esc(a.status)}</b></div><div><small>Local</small><b>YES</b></div></div></article>`).join('')}
const JOBS=[['✍️','Fast Copy Pack','Write a clean listing, caption, or message for a real customer.',250],['📣','Sponsor Pitch','Create a short pitch to acquire a sponsor or referral partner.',400],['🛍️','Listing Engine','Generate titles, benefits, FAQs, and a call to action.',600],['🔎','Research Snapshot','Turn supplied notes into a concise structured brief.',800],['🎬','Short Video Kit','Hook, script, caption, and thumbnail copy.',1000],['🧰','Workflow Setup','Build a reusable AI-assisted work process for a client.',2500]];
function renderJobs(){document.getElementById('jobGrid').innerHTML=JOBS.map((j,i)=>`<article class="job"><div class="jobTop"><div class="avatar">${j[0]}</div><span class="tag">REAL CUSTOMER</span></div><h3>${j[1]}</h3><p>${j[2]}</p><div class="jobReward">${fmt(j[3])} <small>suggested sats</small></div><div class="btns"><button class="btn primary full" onclick="loadJob(${i})">Build deliverable</button></div></article>`).join('')}
function loadJob(i){const j=JOBS[i];document.getElementById('taskInput').value=j[2]+' Customer details: ';document.getElementById('taskType').value=i===1?'pitch':i===2?'listing':i===3?'brief':i===4?'social':'reply';showView('earn');setTimeout(()=>document.getElementById('taskInput').focus(),300)}
function renderActivity(){const box=document.getElementById('activity');if(!S.activity.length){box.innerHTML='<div class="empty">No evolution events yet.</div>';return}box.innerHTML=S.activity.slice(0,12).map(x=>`<div class="item"><div class="itemIcon">${x.type==='win'?'⚡':x.type==='fail'?'☠':x.type==='train'?'🧬':x.type==='birth'?'✦':'✓'}</div><div><b>${esc(x.text)}</b><small>${new Date(x.at).toLocaleString()} · ${esc(x.meta||'local')}</small></div><span>${x.type.toUpperCase()}</span></div>`).join('')}
function renderLedger(){const box=document.getElementById('ledger');if(!S.ledger.length){box.innerHTML='<div class="empty">No verified records yet.</div>';return}box.innerHTML=[...S.ledger].sort((a,b)=>b.at-a.at).map(x=>`<div class="item"><div class="itemIcon">${x.type==='income'?'⚡':'↗'}</div><div><b>${esc(x.memo)}</b><small>${new Date(x.at).toLocaleString()} · ${esc(x.ref)}</small></div><span class="amount">${x.type==='income'?'+':'-'}${fmt(x.sats)}${x.fee?' + '+x.fee+' fee':''}</span></div>`).join('')}
async function refreshPrice(){try{const r=await fetch('https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd',{cache:'no-store'});const d=await r.json();S.btcPrice=Number(d.bitcoin.usd)||S.btcPrice;save();renderAll()}catch(e){}}
function target(){return S.btcPrice?Math.max(1,Math.ceil(.10/S.btcPrice*1e8)):100}
function startRound(){if(timerHandle)clearInterval(timerHandle);S.round={id:id('ROUND'),started:Date.now(),ends:Date.now()+120000,earned:0,target:target(),active:true};log('birth','Survival contract started',fmt(S.round.target)+' sats required');save();timerHandle=setInterval(tick,250);renderAll();generatePitch()}
function tick(){if(!S.round?.active){clearInterval(timerHandle);return}if(Date.now()>=S.round.ends){finishRound();return}renderRound()}
function renderRound(){const r=S.round,tm=document.getElementById('timer'),bar=document.getElementById('roundBar');if(!r){tm.textContent='02:00';bar.style.width='100%';document.getElementById('roundEarned').textContent='0 sats';document.getElementById('targetSats').textContent=fmt(target())+' sats';document.getElementById('coreStatus').textContent='IDLE';return}const left=Math.max(0,r.ends-Date.now()),sec=Math.ceil(left/1000),m=Math.floor(sec/60),s=sec%60;tm.textContent=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');tm.classList.toggle('danger',sec<=20);bar.style.width=Math.max(0,left/120000*100)+'%';document.getElementById('roundEarned').textContent=fmt(r.earned)+' sats';document.getElementById('targetSats').textContent=fmt(r.target)+' sats';document.getElementById('coreStatus').textContent=r.active?'SURVIVAL LIVE':r.success?'SURVIVED':'CEASED';document.getElementById('coreOrb').style.filter=r.active?'none':r.success?'none':'grayscale(1)'}
function finishRound(){if(timerHandle)clearInterval(timerHandle);const r=S.round;if(!r?.active)return;r.active=false;r.success=r.earned>=r.target;if(r.success){S.wins++;S.xp+=100;log('win','Generation survived','Verified '+fmt(r.earned)+' sats');breedAgents(true)}else{S.fails++;log('fail','Generation ceased','Target missed by '+fmt(Math.max(0,r.target-r.earned))+' sats');evolve(false)}save();renderAll()}
function ceaseCurrent(){if(S.round?.active){S.round.ends=Date.now();finishRound()}else{log('fail','Generation manually ceased','Owner command');S.fails++;evolve(false);save();renderAll()}}
