const $=id=>document.getElementById(id),targets=[13,13,12,12];let live=false,poll=null;
function fresh(){return{agent:{id:'agent-demo-01',generation:1,status:'alive',specialty:'compress',strategy:'balanced',fitness:.25,temperature:.45,maxTokens:240},cycle:{number:1,quarterIndex:1,status:'running',revenueCents:0,targetCents:13,jobs:0,progress:0,remainingSeconds:900},hour:{revenueCents:0,targetCents:50,progress:0},offspring:[],events:[{t:Date.now(),m:'Demo organism born. No real payment activity.'}]}}
let state=fresh();
function money(c){return'$'+(Number(c||0)/100).toFixed(2)}function time(s){s=Math.max(0,Math.floor(s||0));return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>$('toast').classList.remove('show'),1600)}
function log(m){state.events.unshift({t:Date.now(),m});state.events=state.events.slice(0,40)}
function render(){const a=state.agent,c=state.cycle,h=state.hour;$('topState').textContent=live?'LIVE ALIVE':'DEMO ALIVE';$('modeState').textContent=live?'LIVE WORKER':'LOCAL DEMO';$('modeState').className=live?'mint':'amber';$('orbFitness').textContent=Number(a.fitness).toFixed(a.fitness<10?3:2).replace(/0+$/,'').replace(/\.$/,'');$('nextFitness').textContent=(Number(a.fitness)*2.5).toFixed(4).replace(/0+$/,'').replace(/\.$/,'');$('orbAgent').textContent='GEN-'+String(a.generation).padStart(2,'0')+' · '+String(a.strategy).toUpperCase();$('orbSub').textContent='quarter '+c.quarterIndex+' · '+(live?'live organism':'demo organism');$('agentState').textContent=a.id;$('generationState').textContent=a.generation;$('specialtyState').textContent=a.specialty;$('strategyState').textContent=a.strategy;$('cycleMoney').textContent=money(c.revenueCents)+' / '+money(c.targetCents);$('hourMoney').textContent=money(h.revenueCents)+' / '+money(h.targetCents);$('hourMetric').textContent=money(h.targetCents);$('cycleBar').style.width=Math.min(100,(c.revenueCents/Math.max(1,c.targetCents))*100)+'%';$('hourBar').style.width=Math.min(100,(h.revenueCents/Math.max(1,h.targetCents))*100)+'%';$('geneFitness').textContent=Number(a.fitness).toFixed(4).replace(/0+$/,'').replace(/\.$/,'');$('geneTemp').textContent=Number(a.temperature??.45).toFixed(2);$('geneTokens').textContent=a.maxTokens??240;
$('quarters').innerHTML=targets.map((t,i)=>{const q=i+1,is=i===c.quarterIndex-1,rev=is?c.revenueCents:0,p=is?Math.min(100,rev/Math.max(1,c.targetCents)*100):0;return`<article class="quarter ${is?'active':''}" style="--p:${p}%"><div class="qtop"><b>Q${q}</b><span>${is?time(c.remainingSeconds):'15:00'}</span></div><div class="qmoney">${money(is?rev:0)}</div><small>target ${money(is?c.targetCents:t)}</small></article>`}).join('');
const offspring=state.offspring||[];$('tree').innerHTML=`<article class="node"><b>${a.id.slice(0,18)}</b><small>GEN ${a.generation} · ${a.status}</small></article>`+(offspring.length?offspring.slice(-5).map(o=>`<span class="arrow">→</span><article class="node"><b>${String(o.id).slice(0,18)}</b><small>GEN ${o.generation||o.genome?.generation||'?'} · $0 spend</small></article>`).join(''):'<span class="arrow">→</span><article class="node"><b>No offspring yet</b><small>reach a quarter target</small></article>');
$('log').innerHTML=(state.events||[]).map(e=>`<div class="event"><time>${new Date(e.t).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</time><p>${escapeHtml(e.m)}</p></div>`).join('')}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function evolve(success){const p=state.agent,old={...p};p.generation++;p.id='agent-demo-'+String(p.generation).padStart(2,'0');p.fitness=Math.round(p.fitness*2.5*10000)/10000;p.parentId=old.id;if(success){state.offspring.push({id:'offspring-'+String(state.offspring.length+1).padStart(2,'0'),generation:p.generation,parentId:old.id});log('Quarter survived. Logical offspring created with $0 spending power.')}else{const list=['balanced','creative','strict'];p.strategy=list[(list.indexOf(p.strategy)+1)%list.length];p.temperature=Math.min(.85,p.temperature+.1);p.maxTokens=Math.min(420,p.maxTokens+24);log('Quarter failed. Previous strategy marked dead; mutated replacement started.')}state.cycle.number++;state.cycle.quarterIndex=(state.cycle.quarterIndex%4)+1;state.cycle.revenueCents=0;state.cycle.jobs=0;state.cycle.targetCents=targets[state.cycle.quarterIndex-1];state.cycle.remainingSeconds=900}
$('jobBtn').onclick=()=>{if(live)return toast('Demo controls disabled in live mode');state.cycle.revenueCents++;state.cycle.jobs++;state.hour.revenueCents++;log('Demo paid job recorded: +$0.01 (simulation only).');if(state.cycle.revenueCents>=state.cycle.targetCents)evolve(true);render()};
$('advanceBtn').onclick=()=>{if(live)return toast('Live cycles advance on the Worker');const success=state.cycle.revenueCents>=state.cycle.targetCents;evolve(success);if(state.cycle.quarterIndex===1){if(state.hour.revenueCents>=state.hour.targetCents){state.hour.targetCents=Math.round(state.hour.targetCents*2.5);log('Hour target survived. Next hourly target multiplied by 2.5.')}else log('Hour target missed. Revenue target remains unchanged.');state.hour.revenueCents=0}render()};
$('resetBtn').onclick=()=>{if(live)return toast('Disconnect to reset demo');state=fresh();render();toast('Demo reset')};
$('saveBtn').onclick=()=>{localStorage.setItem('pennyspawn_q_worker',$('workerUrl').value.trim().replace(/\/$/,''));toast('Worker URL saved')};
async function connect(){const base=$('workerUrl').value.trim().replace(/\/$/,'');if(!/^https:\/\//i.test(base))return toast('Use an HTTPS Worker URL');try{const r=await fetch(base+'/api/public/status',{cache:'no-store'});if(!r.ok)throw new Error('status '+r.status);const s=await r.json();live=true;state.agent={...s.agent,temperature:.45,maxTokens:240};state.cycle=s.cycle;state.hour=s.hour;state.offspring=s.latestOffspring?[s.latestOffspring]:[];state.events=[{t:Date.now(),m:'Connected to live private Worker.'}];render();clearInterval(poll);poll=setInterval(connect,15000);localStorage.setItem('pennyspawn_q_worker',base)}catch(e){live=false;clearInterval(poll);poll=null;log('Connection failed: '+e.message);render();toast('Worker not reachable')}}
$('connectBtn').onclick=connect;const saved=localStorage.getItem('pennyspawn_q_worker')||'';$('workerUrl').value=saved;if(saved)setTimeout(connect,350);render();setInterval(()=>{if(!live&&state.cycle.remainingSeconds>0){state.cycle.remainingSeconds--;render()}},1000);
