import{app,$,KEYS,seedOwner,registerAccount,loginAccount,accountExists,loadState,saveSettings,setSession,sessionUser,clearSession,esc,money,short,clock,validBase,validBtc,toast}from'./state.js';
import{portfolio,startWallets,stopWallets,startMarket,stopModel,startEngine,stopEngine,runTool}from'./runtime.js';
const MON=window.PENNYSPAWN_MONETIZATION||{};
let lastFrame=performance.now(),fps=0,fx={beam:0,particles:[]},adsLoaded=false;
export function switchAuth(mode){app.authMode=mode;$('loginTab').classList.toggle('active',mode==='login');$('registerTab').classList.toggle('active',mode==='register');$('confirmRow').classList.toggle('hidden',mode==='login');$('authConfirm').required=mode==='register';$('authSubmit').querySelector('span').textContent=mode==='login'?'Enter owner dashboard':'Create local profile';$('authError').textContent=''}
async function handleAuth(e){e.preventDefault();$('authSubmit').disabled=true;$('authError').textContent='';try{app.currentUser=app.authMode==='login'?await loginAccount($('authUser').value,$('authPass').value):await registerAccount($('authUser').value,$('authPass').value,$('authConfirm').value);app.spectator=false;setSession(app.currentUser);openApp()}catch(err){$('authError').textContent=err.message||String(err)}finally{$('authSubmit').disabled=false}}
function openGuest(){app.spectator=true;app.currentUser='';setSession('spectator');openApp()}
function openApp(){loadState();$('authGate').classList.add('hidden');$('appShell').setAttribute('aria-hidden','false');$('bottomDock').classList.remove('hidden');document.body.classList.remove('auth-open');$('settingsBtn').style.display=app.spectator?'none':'';populateSettings();showView('home');startMarket();startWallets();render();resizeCanvases();if(!app.spectator&&app.settings.baseWallet)setTimeout(startEngine,500)}
function logout(){stopEngine();stopWallets();stopModel();app.currentUser='';app.spectator=false;clearSession();$('appShell').setAttribute('aria-hidden','true');$('bottomDock').classList.add('hidden');$('authGate').classList.remove('hidden');document.body.classList.add('auth-open');closeSettings()}
function showView(name){app.activeView=name;document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===name));document.querySelectorAll('.dock-btn').forEach(b=>b.classList.toggle('active',b.dataset.viewTarget===name));window.scrollTo({top:0,behavior:'smooth'});setTimeout(resizeCanvases,60)}
function populateSettings(){$('walletAddress').value=app.settings.baseWallet||'';$('btcAddress').value=app.settings.btcWallet||'';$('cycleMinutes').value=app.settings.cycleMinutes;$('cycleMinutesLabel').textContent=`${app.settings.cycleMinutes} min`;$('skillsInput').value=app.settings.skills||'';$('rpcUrl').value=app.settings.rpc;const radio=document.querySelector(`input[name=modelChoice][value=${app.settings.model}]`);if(radio)radio.checked=true}
function openSettings(){if(app.spectator)return toast('Owner login required');populateSettings();$('settingsSheet').classList.add('open');$('settingsSheet').setAttribute('aria-hidden','false')}
function closeSettings(){$('settingsSheet').classList.remove('open');$('settingsSheet').setAttribute('aria-hidden','true')}
function commitSettings(){const base=$('walletAddress').value.trim(),btc=$('btcAddress').value.trim(),rpc=$('rpcUrl').value.trim();if(base&&!validBase(base))throw Error('Invalid public Base address.');if(btc&&!validBtc(btc))throw Error('Bitcoin address format not recognized.');if(!/^https:\/\//i.test(rpc))throw Error('RPC must use HTTPS.');saveSettings({baseWallet:base,btcWallet:btc,cycleMinutes:Math.max(2,Math.min(60,Number($('cycleMinutes').value)||10)),skills:$('skillsInput').value.trim().slice(0,600),rpc,model:document.querySelector('input[name=modelChoice]:checked')?.value||'lite'});closeSettings();stopModel();startWallets();startEngine();toast('Saved and launched')}
export function render(){const total=portfolio(),runs=Number(localStorage.getItem(KEYS.runs)||0),remaining=app.agent.cycleEnd?Math.max(0,(app.agent.cycleEnd-Date.now())/1000):0;$('portfolioValue').textContent=money(total,2);$('sessionReceipts').textContent='+'+money(app.wallet.sessionUsd,2);$('receiptCount').textContent=`${app.wallet.receipts} incoming event${app.wallet.receipts===1?'':'s'}`;$('toolRuns').textContent=String(runs);$('usdcBalance').textContent=money(app.wallet.usdc,6);$('btcBalance').textContent=`${app.wallet.btc.toFixed(8)} BTC`;$('baseAddressShort').textContent=short(app.settings.baseWallet);$('btcAddressShort').textContent=short(app.settings.btcWallet);$('baseBlock').textContent=app.wallet.baseHealthy?`Base block ${app.wallet.baseBlock}`:'not connected';$('btcNetwork').textContent=app.wallet.btcHealthy?'confirmed chain balance':'not connected';$('baseStatus').textContent=app.wallet.baseHealthy?'live':app.settings.baseWallet?'connecting':'not configured';$('btcStatus').textContent=app.wallet.btcHealthy?'live':app.settings.btcWallet?'connecting':'not configured';$('computeRoute').textContent=app.modelDevice==='webgpu'?'iPhone GPU · WebGPU':app.modelDevice==='wasm'?'iPhone CPU · WASM':navigator.gpu?'GPU available':'CPU fallback';$('computeLabel').textContent=$('computeRoute').textContent.toUpperCase();$('toolDevice').textContent=$('computeRoute').textContent;$('modelStatus').textContent=app.modelReady?`${app.modelName} ready`:app.modelLoading?'downloading':'not loaded';$('modelLabel').textContent=app.settings.model==='deep'?'Qwen2.5 Deep':'SmolLM2 Lite';$('reactorState').textContent=app.engine?'AGENT LIVE':app.modelReady?'MODEL READY':'IDLE';$('topState').textContent=app.engine?'RUNNING':app.wallet.baseHealthy||app.wallet.btcHealthy?'WALLET LIVE':'WAITING';$('statusDot').className=app.engine||app.wallet.baseHealthy||app.wallet.btcHealthy?'online':'';$('agentName').textContent=app.agent.id;$('agentStatus').textContent=app.agent.status;$('cycleClock').textContent=app.agent.cycleEnd?clock(remaining):'--:--';$('strategyName').textContent=app.agent.strategy;$('strategyWhy').textContent=app.agent.why;$('nextAction').textContent=app.agent.nextAction;$('generationValue').textContent=app.agent.generation;$('fitnessValue').textContent=app.agent.fitness;$('retiredValue').textContent=app.agent.retired.length;$('offspringValue').textContent=app.agent.offspring.length;$('engineBtn').querySelector('span').textContent=app.engine?'Pause local agent':'Start local agent';$('earnVerified').textContent='+'+money(app.wallet.sessionUsd,2);renderTree();renderLog();renderMonetization();renderMarket()}
function renderTree(){const nodes=[...app.agent.retired.slice(-3),{id:app.agent.id,generation:app.agent.generation,status:'active'},...app.agent.offspring.slice(-3)];$('tree').innerHTML=nodes.map((n,i)=>`${i?'<span class="arrow">→</span>':''}<article class="node ${n.status==='active'?'active':n.status==='retired'?'dead':''}"><b>${esc(n.id)}</b><small>GEN ${n.generation} · ${esc(n.status)}</small></article>`).join('')}
function renderLog(){$('log').innerHTML=app.agent.events.map(e=>`<div class="event"><time>${new Date(e.t).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</time><p>${esc(e.m)}</p></div>`).join('')}
function renderMarket(){for(const[id,asset]of[['btcPrice','BTC'],['ethPrice','ETH'],['solPrice','SOL']])$(id).textContent=app.market.prices[asset]?money(app.market.prices[asset],asset==='BTC'?0:2):'—';convert()}
function convert(){const amount=Number($('convertAmount').value||0),from=$('convertFrom').value,to=$('convertTo').value,usd=amount*(app.market.prices[from]||0),result=to==='USD'?usd:usd/(app.market.prices[to]||Infinity);$('convertResult').textContent=Number.isFinite(result)?`${result.toLocaleString(undefined,{maximumFractionDigits:8})} ${to}`:'—'}
const adReady=()=>/^ca-pub-\d{16}$/.test(MON.adsenseClient||'');
function renderMonetization(){const ready=adReady(),consent=localStorage.getItem(KEYS.consent);$('monetizationState').textContent=ready&&consent==='accepted'?'LIVE':'SETUP';$('adState').textContent=ready?(consent==='accepted'?'ads enabled':'waiting for consent'):'publisher ID missing';$('adEngineStatus').textContent=ready?'configured':'disabled';$('earnAds').textContent=ready?'READY':'NOT LIVE';$('earnAdsCopy').textContent=ready?'Awaiting visitor consent and AdSense approval.':'Add an approved AdSense publisher ID to activate.';$('publisherStatus').textContent=ready?MON.adsenseClient:'missing';$('consentStatus').textContent=consent||'not decided';const usdc=MON.baseUsdcAddress||'',btc=MON.bitcoinAddress||'';$('supportUsdcBtn').disabled=!validBase(usdc);$('supportBtcBtn').disabled=!validBtc(btc);$('supportUsdcText').textContent=validBase(usdc)?short(usdc):'owner address not published';$('supportBtcText').textContent=validBtc(btc)?short(btc):'owner address not published';$('earnTips').textContent=validBase(usdc)||validBtc(btc)?'READY':'NOT LIVE';$('earnTipsCopy').textContent=validBase(usdc)||validBtc(btc)?'Public payment buttons are active.':'Publish public BTC or Base addresses in monetization-config.js.'}
function openConsent(){$('consentSheet').classList.add('open');$('consentSheet').setAttribute('aria-hidden','false')}
function closeConsent(){$('consentSheet').classList.remove('open');$('consentSheet').setAttribute('aria-hidden','true')}
function loadAds(){if(adsLoaded||!adReady()||localStorage.getItem(KEYS.consent)!=='accepted')return;adsLoaded=true;const s=document.createElement('script');s.async=true;s.crossOrigin='anonymous';s.src=`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${encodeURIComponent(MON.adsenseClient)}`;s.onload=()=>{createAd('heroAdUnit',MON.adsenseHeroSlot);createAd('toolAdUnit',MON.adsenseToolSlot)};document.head.appendChild(s)}
function createAd(id,slot){const el=$(id);if(!el||!/^[0-9]+$/.test(slot||'')){if(el)el.textContent='AdSense script ready; ad-unit slot missing.';return}el.innerHTML=`<ins class="adsbygoogle" style="display:block;width:100%" data-ad-client="${esc(MON.adsenseClient)}" data-ad-slot="${esc(slot)}" data-ad-format="auto" data-full-width-responsive="true"></ins>`;try{(window.adsbygoogle=window.adsbygoogle||[]).push({})}catch{}}
function support(asset){const addr=asset==='USDC'?MON.baseUsdcAddress:MON.bitcoinAddress;if(asset==='USDC'&&validBase(addr)){navigator.clipboard?.writeText(addr);toast('Base USDC address copied')}else if(asset==='BTC'&&validBtc(addr)){location.href=`bitcoin:${addr}`}else toast('Owner has not published this address')}
const reactor=$('reactor'),rctx=reactor.getContext('2d'),agentCanvas=$('agentCanvas'),actx=agentCanvas.getContext('2d');
export function resizeCanvases(){for(const[c,ctx]of[[reactor,rctx],[agentCanvas,actx]]){const r=c.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1);c.width=Math.max(1,r.width*d);c.height=Math.max(1,r.height*d);ctx.setTransform(d,0,0,d,0,0)}}
function beam(){fx.beam=1;for(let i=0;i<22;i++){const a=Math.random()*Math.PI*2;fx.particles.push({x:.5,y:.55,vx:Math.cos(a)*.006,vy:Math.sin(a)*.006,life:1})}}window.PS_BEAM=beam;
function drawOrb(ctx,c,now,isAgent){const r=c.getBoundingClientRect(),w=r.width,h=r.height,t=now/1000;ctx.clearRect(0,0,w,h);const x=w*.5,y=h*.54,rad=Math.min(w,h)*(isAgent?.17:.16)+Math.sin(t*2.1)*3,g=ctx.createRadialGradient(x-rad*.2,y-rad*.25,4,x,y,rad*1.35);g.addColorStop(0,'rgba(255,255,255,.95)');g.addColorStop(.18,app.engine?'rgba(113,255,173,.9)':'rgba(98,220,255,.8)');g.addColorStop(1,'rgba(5,8,14,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,rad,0,Math.PI*2);ctx.fill();for(let i=1;i<6;i++){ctx.strokeStyle=`rgba(113,255,173,${.11/i})`;ctx.beginPath();ctx.arc(x,y,rad+i*22+Math.sin(t+i)*2,0,Math.PI*2);ctx.stroke()}ctx.strokeStyle='rgba(169,140,255,.65)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,rad+11,t,t+Math.PI*1.55);ctx.stroke();if(isAgent&&fx.beam>0){ctx.strokeStyle=`rgba(255,111,141,${fx.beam})`;ctx.lineWidth=8+fx.beam*8;ctx.beginPath();ctx.moveTo(w*.83,h*.18);ctx.lineTo(x,y);ctx.stroke();fx.beam=Math.max(0,fx.beam-.025)}if(isAgent){fx.particles=fx.particles.filter(p=>p.life>0);for(const p of fx.particles){p.x+=p.vx;p.y+=p.vy;p.life-=.018;ctx.globalAlpha=p.life;ctx.fillStyle='#ff6f8d';ctx.beginPath();ctx.arc(p.x*w,p.y*h,2.5,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}}
function frame(now){const dt=now-lastFrame;lastFrame=now;fps=fps*.9+(dt?1000/dt:0)*.1;$('reactorFps').textContent=`${Math.round(fps)} FPS`;drawOrb(rctx,reactor,now,false);drawOrb(actx,agentCanvas,now,true);requestAnimationFrame(frame)}
function bindEvents(){$('loginTab').onclick=()=>switchAuth('login');$('registerTab').onclick=()=>switchAuth('register');$('authForm').onsubmit=handleAuth;$('spectatorBtn').onclick=openGuest;$('revealPassBtn').onclick=()=>{const p=$('authPass');p.type=p.type==='password'?'text':'password';$('revealPassBtn').textContent=p.type==='password'?'Show':'Hide'};document.querySelectorAll('[data-view-target]').forEach(b=>b.onclick=()=>showView(b.dataset.viewTarget));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));$('settingsBtn').onclick=openSettings;$('closeSettingsBtn').onclick=closeSettings;$('sheetBackdrop').onclick=closeSettings;$('cycleMinutes').oninput=()=>$('cycleMinutesLabel').textContent=`${$('cycleMinutes').value} min`;$('saveSettingsBtn').onclick=()=>{try{commitSettings()}catch(e){toast(e.message)}};$('logoutBtn').onclick=logout;$('engineBtn').onclick=()=>app.engine?stopEngine():startEngine();document.querySelectorAll('#toolMode button').forEach(b=>b.onclick=()=>{app.toolMode=b.dataset.tool;document.querySelectorAll('#toolMode button').forEach(x=>x.classList.toggle('active',x===b))});$('runToolBtn').onclick=runTool;$('copyToolBtn').onclick=async()=>{await navigator.clipboard?.writeText($('toolOutput').textContent);toast('Copied')};$('convertAmount').oninput=convert;$('convertFrom').onchange=convert;$('convertTo').onchange=convert;$('supportUsdcBtn').onclick=()=>support('USDC');$('supportBtcBtn').onclick=()=>support('BTC');$('privacyBtn').onclick=openConsent;$('acceptAdsBtn').onclick=()=>{localStorage.setItem(KEYS.consent,'accepted');closeConsent();loadAds();renderMonetization()};$('rejectAdsBtn').onclick=()=>{localStorage.setItem(KEYS.consent,'rejected');closeConsent();renderMonetization()};$('installBtn').onclick=async()=>{if(app.installPrompt){app.installPrompt.prompt();await app.installPrompt.userChoice;app.installPrompt=null}else toast('iPhone: Share → Add to Home Screen')};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();app.installPrompt=e});window.addEventListener('resize',resizeCanvases)}
export function bootUI(){seedOwner();bindEvents();switchAuth('login');if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=6').catch(()=>{});const saved=sessionUser();if(saved==='spectator')openGuest();else if(saved&&accountExists(saved)){app.currentUser=saved;openApp()}resizeCanvases();requestAnimationFrame(frame);setInterval(render,1000);renderMonetization();if(localStorage.getItem(KEYS.consent)==='accepted')loadAds()}
